//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_TNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonent()
        {
            this.Abonent_Service = new HashSet<Abonent_Service>();
            this.Abonent_Tariff = new HashSet<Abonent_Tariff>();
            this.AbonentPayment = new HashSet<AbonentPayment>();
        }
    
        public int ID { get; set; }
        public string Number { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Paramonic { get; set; }
        public string PassportNumber { get; set; }
        public string PassportSeries { get; set; }
        public string PassportIssueDate { get; set; }
        public string ContractNumber { get; set; }
        public string ContractConclusionDate { get; set; }
        public int ContractType { get; set; }
        public string ContractTerminationDate { get; set; }
        public string ContractTerminationReason { get; set; }
        public string AccountNumber { get; set; }
        public string EquipmentSerialNumber { get; set; }
        public string RentLeasingInfo { get; set; }
        public string Phone { get; set; }
        public int Sex { get; set; }
        public string DateofBirth { get; set; }
        public string Email { get; set; }
        public Nullable<int> PassportIssueOrganization { get; set; }
        public Nullable<int> RegistrationAddress { get; set; }
    
        public virtual ContractType ContractType1 { get; set; }
        public virtual PassportIssueOrganization PassportIssueOrganization1 { get; set; }
        public virtual RegistrationAddress RegistrationAddress1 { get; set; }
        public virtual Sex Sex1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonent_Service> Abonent_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonent_Tariff> Abonent_Tariff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbonentPayment> AbonentPayment { get; set; }
    }
}
