//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_TNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRMRequest()
        {
            this.RequestToEmployee = new HashSet<RequestToEmployee>();
        }
    
        public int ID { get; set; }
        public string RequestNum { get; set; }
        public string CreationDate { get; set; }
        public string AccountNumber { get; set; }
        public int Service { get; set; }
        public int ServiceType { get; set; }
        public int Status { get; set; }
        public string ProblemDescription { get; set; }
        public string ClosingDate { get; set; }
        public int ProblemType { get; set; }
    
        public virtual ProblemType ProblemType1 { get; set; }
        public virtual Service Service1 { get; set; }
        public virtual ServiceType ServiceType1 { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestToEmployee> RequestToEmployee { get; set; }
    }
}
