//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_TNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainNetworkEquipment
    {
        public int ID { get; set; }
        public string SerialNumber { get; set; }
        public string Name { get; set; }
        public double Frequency { get; set; }
        public int DataTransmissionTechnology { get; set; }
    
        public virtual DataTransmissionTechnology DataTransmissionTechnology1 { get; set; }
    }
}
