//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_TNS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TNSEntities : DbContext
    {
        public TNSEntities()
            : base("name=TNSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent> Abonent { get; set; }
        public virtual DbSet<Abonent_Service> Abonent_Service { get; set; }
        public virtual DbSet<Abonent_Tariff> Abonent_Tariff { get; set; }
        public virtual DbSet<AbonentNetworkEquipment> AbonentNetworkEquipment { get; set; }
        public virtual DbSet<AbonentPayment> AbonentPayment { get; set; }
        public virtual DbSet<AccessNetworkEquipment> AccessNetworkEquipment { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<ContractType> ContractType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<CRMRequest> CRMRequest { get; set; }
        public virtual DbSet<DataTransmissionStandart> DataTransmissionStandart { get; set; }
        public virtual DbSet<DataTransmissionTechnology> DataTransmissionTechnology { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<MainNetworkEquipment> MainNetworkEquipment { get; set; }
        public virtual DbSet<PassportIssueOrganization> PassportIssueOrganization { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<ProblemType> ProblemType { get; set; }
        public virtual DbSet<RegistrationAddress> RegistrationAddress { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<RequestToEmployee> RequestToEmployee { get; set; }
        public virtual DbSet<ResidenceAddress> ResidenceAddress { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceKind> ServiceKind { get; set; }
        public virtual DbSet<ServiceType> ServiceType { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tariff> Tariff { get; set; }
    }
}
