//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_TNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationAddress()
        {
            this.Abonent = new HashSet<Abonent>();
        }
    
        public int RegAddID { get; set; }
        public int RegAddContry { get; set; }
        public int RegAddCity { get; set; }
        public int RegAddStreet { get; set; }
        public string RegAddHouse { get; set; }
        public string RegAddApartment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonent> Abonent { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Street Street { get; set; }
    }
}
