//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_TNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestToEmployee
    {
        public int EmpID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool isHoliday { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
        public int RtEID { get; set; }
    
        public virtual CRMRequest CRMRequest { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
