//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_TNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidenceAddress
    {
        public string number { get; set; }
        public string prefix_code { get; set; }
        public string raion { get; set; }
        public string prefix { get; set; }
        public string house { get; set; }
    }
}
