//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_TNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tariff()
        {
            this.Abonent_Tariff = new HashSet<Abonent_Tariff>();
        }
    
        public int TariffID { get; set; }
        public string TariffName { get; set; }
        public decimal TariffPrice { get; set; }
        public string InternetConditions { get; set; }
        public string TVConditions { get; set; }
        public string MobileConditions { get; set; }
        public string VideoControlConditions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonent_Tariff> Abonent_Tariff { get; set; }
    }
}
