//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_TNS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TNSEntities : DbContext
    {
        public TNSEntities()
            : base("name=TNSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent> Abonent { get; set; }
        public virtual DbSet<AbonentNetworkEquipment> AbonentNetworkEquipment { get; set; }
        public virtual DbSet<AccessNetworkEquipment> AccessNetworkEquipment { get; set; }
        public virtual DbSet<ContractType> ContractType { get; set; }
        public virtual DbSet<CRMRequest> CRMRequest { get; set; }
        public virtual DbSet<DataTransmissionStandart> DataTransmissionStandart { get; set; }
        public virtual DbSet<DataTransmissionTechnology> DataTransmissionTechnology { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<MainNetworkEquipment> MainNetworkEquipment { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<ProblemType> ProblemType { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceKind> ServiceKind { get; set; }
        public virtual DbSet<ServiceType> ServiceType { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<RequestToEmployee> RequestToEmployee { get; set; }
    }
}
